name: Backup to OneDrive for Business (with Zip and Date Timestamp)

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (zip and rclone)
      - name: Install zip and rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rclone jq

      # Step 3: Generate timestamp and zip the repository
      - name: Zip the repository with date-only timestamp
        run: |
          # Get current date in YYYY-MM-DD format
          timestamp=$(date +'%Y-%m-%d')

          # Create a zip file with the repository contents and date as timestamp
          zip -r "repository-backup-$timestamp.zip" . 

      # Step 4: Configure rclone for OneDrive for Business
      - name: Configure rclone for OneDrive for Business
        run: |
          mkdir -p ~/.config/rclone
          rclone config file

          # Set up the rclone configuration for OneDrive (with Azure credentials)
          echo "[onedrive]" > ~/.config/rclone/rclone.conf
          echo "type = onedrive" >> ~/.config/rclone/rclone.conf
          echo "client_id = ${{ secrets.ONEDRIVE_CLIENT_ID }}" >> ~/.config/rclone/rclone.conf
          echo "client_secret = ${{ secrets.ONEDRIVE_CLIENT_SECRET }}" >> ~/.config/rclone/rclone.conf
          echo "tenant_id = ${{ secrets.ONEDRIVE_TENANT_ID }}" >> ~/.config/rclone/rclone.conf

      # Step 5: Authenticate rclone and upload the zip file to OneDrive for Business
      - name: Authenticate rclone and upload zip
        run: |
          # Authenticate using the stored client credentials
          rclone authorize "onedrive" --token-file ~/.config/rclone/rclone.conf

          # Upload the zip file with the date-only timestamp to OneDrive (change the folder path as needed)
          rclone copy "repository-backup-$timestamp.zip" onedrive:/backup-folder/ --progress

      # Step 6: Clean up the zip file (optional)
      - name: Clean up
        run: |
          rm "repository-backup-$timestamp.zip"
