name: Backup Repository to OneDrive

# Trigger on push to main branch and on schedule (daily at midnight UTC)
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip repository with timestamp
        run: zip -r repo_backup_$(date +'%Y-%m-%d').zip .

      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Set up Rclone config
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Upload backup to OneDrive
        run: |
          rclone copy repo_backup_$(date +'%Y-%m-%d').zip "OneDrive:Repo Backup" -v --create-empty-src-dirs

      # - name: Cleanup old backups
      #   # Remove files older than 7 days from the OneDrive "Repo Backup" directory
      #   run: |
      #     rclone delete --min-age 7d "OneDrive:Repo Backup" -v
